// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/_shared/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function readEnv(name) {
  const value = Deno.env.get(name);
  if (!value) throw new Error(`Env var ausente na edge function mcp: ${name}`);
  return value;
}
function supabaseForUser(ctx) {
  return createClient(
    readEnv("SUPABASE_URL"),
    // fallback: alguns runtimes só têm ANON_KEY, outros só PUBLISHABLE_KEY
    Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? readEnv("SUPABASE_ANON_KEY"),
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o perfil do usu\xE1rio logado no Clilin: id, nome, papel (CLIENT/COMPANY/AFFILIATE/ADMIN), cidade e saldo em centavos.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile, error: pErr } = await sb.from("profiles").select("id, name, city, balance, cnpj, telefone").eq("user_id", ctx.getUserId()).maybeSingle();
    if (pErr) {
      return { content: [{ type: "text", text: pErr.message }], isError: true };
    }
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_offers_default = defineTool2({
  name: "list_offers",
  title: "Listar ofertas ativas",
  description: "Lista ofertas ativas no Clilin, com filtros opcionais por cidade e busca no t\xEDtulo. Retorna id, t\xEDtulo, pre\xE7os, cidade, empresa e cliques.",
  inputSchema: {
    city: z.string().optional().describe("Cidade no formato 'Cidade - UF' (ex: 'Belo Horizonte - MG')."),
    search: z.string().optional().describe("Texto para buscar no t\xEDtulo da oferta."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de ofertas a retornar (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("offers").select("id, title, description, price_old, price_new, city, tags, clicks_count, views_count, expires_at, company_id").eq("active", true).gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("clicks_count", { ascending: false }).limit(Math.min(limit ?? 20, 50));
    if (city) q = q.eq("city", city);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-offers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_offers_default = defineTool3({
  name: "list_my_offers",
  title: "Listar minhas ofertas (empresa)",
  description: "Lista as ofertas da empresa logada, incluindo pausadas e expiradas. S\xF3 funciona se o usu\xE1rio for COMPANY.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data, error } = await sb.from("offers").select("id, title, price_old, price_new, active, expires_at, clicks_count, views_count, city, tags, created_at").eq("company_id", profile.id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/set-offer-active.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var set_offer_active_default = defineTool4({
  name: "set_offer_active",
  title: "Pausar ou reativar oferta",
  description: "Ativa ou pausa uma oferta da empresa logada. Passe active=true para reativar, active=false para pausar.",
  inputSchema: {
    offer_id: z2.string().uuid().describe("ID da oferta."),
    active: z2.boolean().describe("true para reativar, false para pausar.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id, active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("offers").update({ active }).eq("id", offer_id).select("id, title, active").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Oferta n\xE3o encontrada ou sem permiss\xE3o." }], isError: true };
    return {
      content: [{ type: "text", text: `Oferta "${data.title}" ${data.active ? "reativada" : "pausada"}.` }],
      structuredContent: { offer: data }
    };
  }
});

// src/lib/mcp/tools/list-my-leads.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_leads_default = defineTool5({
  name: "list_my_leads",
  title: "Listar meus leads (empresa)",
  description: "Lista os leads recebidos pela empresa logada, mais recentes primeiro.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("M\xE1ximo de leads (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data, error } = await sb.from("leads").select("id, name, phone, email, offer_id, created_at, status").eq("company_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-coupons.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_coupons_default = defineTool6({
  name: "list_my_coupons",
  title: "Listar cupons da empresa",
  description: "Lista cupons emitidos para a empresa logada, com filtro opcional por status (ISSUED, REDEEMED, EXPIRED).",
  inputSchema: {
    status: z4.enum(["ISSUED", "REDEEMED", "EXPIRED"]).optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    let q = sb.from("coupons").select("id, code, customer_name, customer_phone, offer_id, status, expires_at, redeemed_at, created_at").eq("company_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { coupons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-earnings.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_my_earnings_default = defineTool7({
  name: "get_my_earnings",
  title: "Meu saldo e transa\xE7\xF5es",
  description: "Retorna o saldo atual (em centavos) e as \xFAltimas transa\xE7\xF5es do usu\xE1rio logado. \xDAtil para divulgadores e empresas verem movimenta\xE7\xF5es.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("N\xBA de transa\xE7\xF5es (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id, balance").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data: txs, error } = await sb.from("transactions").select("id, type, amount, description, created_at, offer_id").eq("user_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      balance_cents: profile.balance ?? 0,
      balance_reais: ((profile.balance ?? 0) / 100).toFixed(2),
      transactions: txs ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/admin-overview.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
var admin_overview_default = defineTool8({
  name: "admin_overview",
  title: "Overview admin",
  description: "Retorna totais gerais da plataforma: n\xBA de empresas, divulgadores, clientes, ofertas ativas, leads, cupons e saques pendentes. Apenas para usu\xE1rios com papel ADMIN.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const isAdmin = (roles ?? []).some((r) => r.role === "ADMIN");
    if (!isAdmin) {
      return { content: [{ type: "text", text: "Acesso negado: requer papel ADMIN." }], isError: true };
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const [companies, affiliates, clients, offersActive, leads, couponsIssued, couponsRedeemed, withdrawalsPending] = await Promise.all([
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "COMPANY"),
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "AFFILIATE"),
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "CLIENT"),
      sb.from("offers").select("*", { count: "exact", head: true }).eq("active", true).gt("expires_at", nowIso),
      sb.from("leads").select("*", { count: "exact", head: true }),
      sb.from("coupons").select("*", { count: "exact", head: true }).eq("status", "ISSUED"),
      sb.from("coupons").select("*", { count: "exact", head: true }).eq("status", "REDEEMED"),
      sb.from("withdrawals").select("*", { count: "exact", head: true }).eq("status", "PENDING")
    ]);
    const payload = {
      companies: companies.count ?? 0,
      affiliates: affiliates.count ?? 0,
      clients: clients.count ?? 0,
      active_offers: offersActive.count ?? 0,
      total_leads: leads.count ?? 0,
      coupons_issued: couponsIssued.count ?? 0,
      coupons_redeemed: couponsRedeemed.count ?? 0,
      withdrawals_pending: withdrawalsPending.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-offer.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var create_offer_default = defineTool9({
  name: "create_offer",
  title: "Criar oferta",
  description: "Cria uma nova oferta. Empresa (COMPANY) cria para si pr\xF3pria \u2014 n\xE3o passe company_id. ADMIN pode criar em nome de QUALQUER empresa passando company_id (use `list_companies` ou `find_company` para descobrir o id da empresa desejada). Pre\xE7os em reais (ex: 49.90).",
  inputSchema: {
    title: z6.string().min(3).max(120),
    description: z6.string().optional(),
    price_old: z6.number().positive(),
    price_new: z6.number().positive(),
    city: z6.string(),
    link_destination: z6.string().url(),
    link_type: z6.enum(["WHATSAPP", "WEBSITE", "MENU"]).default("WHATSAPP"),
    tags: z6.array(z6.string()).optional(),
    images: z6.array(z6.string().url()).optional(),
    company_id: z6.string().uuid().optional().describe("UUID da empresa dona da oferta (tabela profiles.id). Obrigat\xF3rio apenas para admins criando em nome de terceiros; empresas comuns devem omitir."),
    bounty: z6.number().positive().optional().describe("Recompensa por resgate: quanto a empresa paga quando um cliente novo resgata o cupom na loja, em reais. Minimo R$5,00. Padrao R$8,00.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let companyId = input.company_id;
    if (!companyId) {
      const { data: prof } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
      if (!prof) return { content: [{ type: "text", text: "Profile n\xE3o encontrado." }], isError: true };
      companyId = prof.id;
    }
    const { data, error } = await sb.from("offers").insert({
      company_id: companyId,
      title: input.title,
      description: input.description ?? null,
      price_old: input.price_old,
      price_new: input.price_new,
      city: input.city,
      link_destination: input.link_destination,
      link_type: input.link_type,
      tags: input.tags ?? [],
      images: input.images ?? [],
      redemption_cost: Math.max(500, Math.round((input.bounty ?? 8) * 100)),
      active: true
    }).select("id, title, price_new, active").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Oferta "${data?.title}" criada.` }], structuredContent: { offer: data } };
  }
});

// src/lib/mcp/tools/update-offer.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var update_offer_default = defineTool10({
  name: "update_offer",
  title: "Editar oferta",
  description: "Atualiza campos de uma oferta existente. S\xF3 envie os campos que quer mudar.",
  inputSchema: {
    offer_id: z7.string().uuid(),
    title: z7.string().min(3).max(120).optional(),
    description: z7.string().optional(),
    price_old: z7.number().positive().optional(),
    price_new: z7.number().positive().optional(),
    city: z7.string().optional(),
    link_destination: z7.string().url().optional(),
    tags: z7.array(z7.string()).optional(),
    images: z7.array(z7.string().url()).optional(),
    bounty: z7.number().positive().optional().describe("Recompensa por resgate em reais (minimo R$5,00).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { bounty, ...rest } = patch;
    const cleaned = Object.fromEntries(Object.entries(rest).filter(([, v]) => v !== void 0));
    if (bounty !== void 0) cleaned.redemption_cost = Math.max(500, Math.round(Number(bounty) * 100));
    if (Object.keys(cleaned).length === 0) return { content: [{ type: "text", text: "Nada para atualizar." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("offers").update(cleaned).eq("id", offer_id).select("id, title").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Oferta n\xE3o encontrada ou sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Oferta "${data.title}" atualizada.` }], structuredContent: { offer: data } };
  }
});

// src/lib/mcp/tools/delete-offer.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^3.25.76";
var delete_offer_default = defineTool11({
  name: "delete_offer",
  title: "Deletar oferta",
  description: "Soft-delete de oferta (marca deleted_at). N\xE3o some do banco, s\xF3 some do site.",
  inputSchema: { offer_id: z8.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("offers").update({ deleted_at: (/* @__PURE__ */ new Date()).toISOString(), active: false }).eq("id", offer_id).select("id, title").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Oferta n\xE3o encontrada ou sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Oferta "${data.title}" deletada.` }] };
  }
});

// src/lib/mcp/tools/list-companies.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z9 } from "npm:zod@^3.25.76";
var list_companies_default = defineTool12({
  name: "list_companies",
  title: "Listar empresas",
  description: "Lista empresas (admin v\xEA todas; empresa v\xEA a pr\xF3pria). Filtro opcional por cidade ou nome.",
  inputSchema: {
    city: z9.string().optional(),
    search: z9.string().optional().describe("Busca parcial por nome ou raz\xE3o social."),
    limit: z9.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ city, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("profiles").select("id, name, city, cnpj, razao_social, email, balance, banned, balance_frozen, created_at").in("user_id", (await sb.from("user_roles").select("user_id").eq("role", "COMPANY")).data?.map((r) => r.user_id) ?? []).limit(limit);
    if (city) q = q.eq("city", city);
    if (search) q = q.or(`name.ilike.%${search}%,razao_social.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const lines = rows.map((c) => `- ${c.name} | id=${c.id} | ${c.city ?? "-"} | CNPJ=${c.cnpj ?? "-"} | saldo=${c.balance ?? 0} | ${c.banned ? "BANIDA" : c.balance_frozen ? "SALDO CONGELADO" : "ok"}`);
    const text = `${rows.length} empresas. Use o campo 'id' como company_id em create_offer/update_offer.
${lines.join("\n")}`;
    return { content: [{ type: "text", text }], structuredContent: { companies: rows } };
  }
});

// src/lib/mcp/tools/list-affiliates.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z10 } from "npm:zod@^3.25.76";
var list_affiliates_default = defineTool13({
  name: "list_affiliates",
  title: "Listar divulgadores",
  description: "Lista divulgadores. S\xF3 admin consegue ver todos.",
  inputSchema: {
    city: z10.string().optional(),
    search: z10.string().optional(),
    limit: z10.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ city, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const roleRows = (await sb.from("user_roles").select("user_id").eq("role", "AFFILIATE")).data ?? [];
    let q = sb.from("profiles").select("id, name, city, cpf, email, balance, banned, balance_frozen, fraud_score, created_at").in("user_id", roleRows.map((r) => r.user_id)).limit(limit);
    if (city) q = q.eq("city", city);
    if (search) q = q.or(`name.ilike.%${search}%,cpf.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `${data?.length ?? 0} divulgadores.` }], structuredContent: { affiliates: data } };
  }
});

// src/lib/mcp/tools/adjust-user-balance.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z11 } from "npm:zod@^3.25.76";
var adjust_user_balance_default = defineTool14({
  name: "adjust_user_balance",
  title: "Ajustar saldo de usu\xE1rio",
  description: "Admin: adiciona (positivo) ou remove (negativo) cr\xE9ditos do saldo em CENTAVOS e registra transa\xE7\xE3o. Ex: 10000 = R$ 100,00.",
  inputSchema: {
    profile_id: z11.string().uuid(),
    amount_cents: z11.number().int().describe("Valor em centavos. Positivo credita, negativo debita."),
    reason: z11.string().min(3)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ profile_id, amount_cents, reason }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data: prof, error: pErr } = await sb.from("profiles").select("balance").eq("id", profile_id).maybeSingle();
    if (pErr || !prof) return { content: [{ type: "text", text: pErr?.message ?? "Usu\xE1rio n\xE3o encontrado / sem permiss\xE3o." }], isError: true };
    const newBalance = (prof.balance ?? 0) + amount_cents;
    const { error: uErr } = await sb.from("profiles").update({ balance: newBalance }).eq("id", profile_id);
    if (uErr) return { content: [{ type: "text", text: uErr.message }], isError: true };
    const { error: tErr } = await sb.from("transactions").insert({
      user_id: profile_id,
      amount: amount_cents,
      type: amount_cents >= 0 ? "DEPOSIT" : "WITHDRAWAL",
      description: `Ajuste manual via MCP: ${reason}`
    });
    if (tErr) return { content: [{ type: "text", text: `Saldo atualizado mas transa\xE7\xE3o falhou: ${tErr.message}` }] };
    return { content: [{ type: "text", text: `Saldo ajustado. Novo saldo: R$ ${(newBalance / 100).toFixed(2)}` }], structuredContent: { balance_cents: newBalance } };
  }
});

// src/lib/mcp/tools/set-user-banned.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z12 } from "npm:zod@^3.25.76";
var set_user_banned_default = defineTool15({
  name: "set_user_banned",
  title: "Banir ou desbanir usu\xE1rio",
  description: "Admin: bane (banned=true) ou desbane (banned=false) um usu\xE1rio.",
  inputSchema: {
    profile_id: z12.string().uuid(),
    banned: z12.boolean(),
    reason: z12.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ profile_id, banned, reason }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const patch = { banned };
    if (banned) {
      patch.banned_at = (/* @__PURE__ */ new Date()).toISOString();
      patch.banned_reason = reason ?? "Banido via MCP";
    } else {
      patch.banned_at = null;
      patch.banned_reason = null;
    }
    const { data, error } = await sb.from("profiles").update(patch).eq("id", profile_id).select("id, name, banned").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Usu\xE1rio n\xE3o encontrado / sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Usu\xE1rio ${data.name} ${data.banned ? "banido" : "desbanido"}.` }] };
  }
});

// src/lib/mcp/tools/set-balance-frozen.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z13 } from "npm:zod@^3.25.76";
var set_balance_frozen_default = defineTool16({
  name: "set_balance_frozen",
  title: "Congelar/descongelar saldo",
  description: "Admin: congela ou descongela o saldo de um usu\xE1rio (bloqueia saques).",
  inputSchema: { profile_id: z13.string().uuid(), frozen: z13.boolean() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ profile_id, frozen }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("profiles").update({ balance_frozen: frozen }).eq("id", profile_id).select("id, name, balance_frozen").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Usu\xE1rio n\xE3o encontrado / sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Saldo de ${data.name} ${data.balance_frozen ? "congelado" : "descongelado"}.` }] };
  }
});

// src/lib/mcp/tools/list-withdrawals.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z14 } from "npm:zod@^3.25.76";
var list_withdrawals_default = defineTool17({
  name: "list_withdrawals",
  title: "Listar solicita\xE7\xF5es de saque",
  description: "Lista saques. Filtre por status (PENDING, APPROVED, REJECTED, PAID).",
  inputSchema: {
    status: z14.string().optional(),
    limit: z14.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("withdrawals").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `${data?.length ?? 0} saques.` }], structuredContent: { withdrawals: data } };
  }
});

// src/lib/mcp/tools/set-withdrawal-status.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z15 } from "npm:zod@^3.25.76";
var set_withdrawal_status_default = defineTool18({
  name: "set_withdrawal_status",
  title: "Aprovar/rejeitar saque",
  description: "Admin: muda status de uma solicita\xE7\xE3o de saque (APPROVED, REJECTED, PAID).",
  inputSchema: {
    withdrawal_id: z15.string().uuid(),
    status: z15.enum(["APPROVED", "REJECTED", "PAID"]),
    note: z15.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ withdrawal_id, status, note }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const patch = { status };
    if (note) patch.admin_note = note;
    if (status === "PAID") patch.paid_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await sb.from("withdrawals").update(patch).eq("id", withdrawal_id).select("id, status, amount").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Saque n\xE3o encontrado / sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Saque marcado como ${data.status}.` }], structuredContent: { withdrawal: data } };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z16 } from "npm:zod@^3.25.76";
var list_cities_default = defineTool19({
  name: "list_cities",
  title: "Listar cidades dispon\xEDveis",
  description: "Lista cidades cadastradas (ativas e inativas). Filtro opcional por estado.",
  inputSchema: {
    state_code: z16.string().length(2).optional(),
    active_only: z16.boolean().default(false)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ state_code, active_only }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("available_cities").select("*").order("state_code").order("city_name");
    if (state_code) q = q.eq("state_code", state_code.toUpperCase());
    if (active_only) q = q.eq("active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `${data?.length ?? 0} cidades.` }], structuredContent: { cities: data } };
  }
});

// src/lib/mcp/tools/set-city-active.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z17 } from "npm:zod@^3.25.76";
var set_city_active_default = defineTool20({
  name: "set_city_active",
  title: "Ativar/desativar cidade",
  description: "Admin: ativa ou desativa uma cidade para cadastros.",
  inputSchema: { city_id: z17.string().uuid(), active: z17.boolean() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ city_id, active }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const patch = { active };
    if (active) patch.activated_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await sb.from("available_cities").update(patch).eq("id", city_id).select("id, city_name, state_code, active").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Cidade n\xE3o encontrada / sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `${data.city_name}/${data.state_code} ${data.active ? "ativada" : "desativada"}.` }] };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z18 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool21({
  name: "list_blog_posts",
  title: "Listar posts do blog",
  description: "Lista posts do blog. Filtre por status (draft, published, scheduled).",
  inputSchema: {
    status: z18.string().optional(),
    limit: z18.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("blog_posts").select("id, title, slug, status, category, published_at, views, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `${data?.length ?? 0} posts.` }], structuredContent: { posts: data } };
  }
});

// src/lib/mcp/tools/publish-blog-post.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z19 } from "npm:zod@^3.25.76";
var publish_blog_post_default = defineTool22({
  name: "publish_blog_post",
  title: "Publicar ou despublicar post",
  description: "Muda status de um post do blog para published/draft.",
  inputSchema: {
    post_id: z19.string().uuid(),
    status: z19.enum(["published", "draft"])
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const patch = { status };
    if (status === "published") patch.published_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await sb.from("blog_posts").update(patch).eq("id", post_id).select("id, title, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Post n\xE3o encontrado / sem permiss\xE3o." }], isError: true };
    return { content: [{ type: "text", text: `Post "${data.title}" -> ${data.status}.` }] };
  }
});

// src/lib/mcp/tools/add-merchant-whatsapp.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z20 } from "npm:zod@^3.25.76";
var add_merchant_whatsapp_default = defineTool23({
  name: "add_merchant_whatsapp",
  title: "Adicionar WhatsApp de resgate",
  description: "Adiciona um n\xFAmero de WhatsApp autorizado a resgatar cupons para a empresa logada.",
  inputSchema: {
    phone: z20.string().regex(/^\+?\d{10,15}$/, "Telefone em formato internacional, s\xF3 d\xEDgitos (ex: 5511999998888)."),
    label: z20.string().optional().describe("Ex: Caixa 1, Balc\xE3o")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ phone, label }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data: prof } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!prof) return { content: [{ type: "text", text: "Profile n\xE3o encontrado." }], isError: true };
    const normalized = phone.replace(/\D/g, "");
    const { data, error } = await sb.from("merchant_whatsapp").insert({
      profile_id: prof.id,
      phone: normalized,
      label: label ?? null,
      verified: false
    }).select("id, phone, label").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `WhatsApp ${data?.phone} adicionado${data?.label ? ` (${data.label})` : ""}.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sukvjgxxuzophzjcojvd";
var mcp_default = defineMcp({
  name: "clilin-mcp",
  title: "Clilin",
  version: "0.2.0",
  instructions: "Ferramentas do Clilin (plataforma de ofertas locais). Use `whoami` primeiro para descobrir o papel do usu\xE1rio. Todas as a\xE7\xF5es respeitam RLS: admins t\xEAm alcance total, empresas mexem s\xF3 nas pr\xF3prias ofertas/leads/cupons, divulgadores veem seu saldo. Opera\xE7\xF5es destrutivas (ban, delete, ajuste de saldo, aprovar saque) devem ser confirmadas com o usu\xE1rio antes de executar.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    // Leitura
    whoami_default,
    list_offers_default,
    list_my_offers_default,
    list_my_leads_default,
    list_my_coupons_default,
    get_my_earnings_default,
    admin_overview_default,
    list_companies_default,
    list_affiliates_default,
    list_withdrawals_default,
    list_cities_default,
    list_blog_posts_default,
    // Escrita
    set_offer_active_default,
    create_offer_default,
    update_offer_default,
    delete_offer_default,
    adjust_user_balance_default,
    set_user_banned_default,
    set_balance_frozen_default,
    set_withdrawal_status_default,
    set_city_active_default,
    publish_blog_post_default,
    add_merchant_whatsapp_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
