// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/_shared/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o perfil do usu\xE1rio logado no Clilin: id, nome, papel (CLIENT/COMPANY/AFFILIATE/ADMIN), cidade e saldo em centavos.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile, error: pErr } = await sb.from("profiles").select("id, name, city, balance, cnpj, telefone").eq("user_id", ctx.getUserId()).maybeSingle();
    if (pErr) {
      return { content: [{ type: "text", text: pErr.message }], isError: true };
    }
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_offers_default = defineTool2({
  name: "list_offers",
  title: "Listar ofertas ativas",
  description: "Lista ofertas ativas no Clilin, com filtros opcionais por cidade e busca no t\xEDtulo. Retorna id, t\xEDtulo, pre\xE7os, cidade, empresa e cliques.",
  inputSchema: {
    city: z.string().optional().describe("Cidade no formato 'Cidade - UF' (ex: 'Belo Horizonte - MG')."),
    search: z.string().optional().describe("Texto para buscar no t\xEDtulo da oferta."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de ofertas a retornar (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("offers").select("id, title, description, price_old, price_new, city, tags, clicks_count, views_count, expires_at, company_id").eq("active", true).gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("clicks_count", { ascending: false }).limit(Math.min(limit ?? 20, 50));
    if (city) q = q.eq("city", city);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-offers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_offers_default = defineTool3({
  name: "list_my_offers",
  title: "Listar minhas ofertas (empresa)",
  description: "Lista as ofertas da empresa logada, incluindo pausadas e expiradas. S\xF3 funciona se o usu\xE1rio for COMPANY.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data, error } = await sb.from("offers").select("id, title, price_old, price_new, active, expires_at, clicks_count, views_count, city, tags, created_at").eq("company_id", profile.id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/set-offer-active.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var set_offer_active_default = defineTool4({
  name: "set_offer_active",
  title: "Pausar ou reativar oferta",
  description: "Ativa ou pausa uma oferta da empresa logada. Passe active=true para reativar, active=false para pausar.",
  inputSchema: {
    offer_id: z2.string().uuid().describe("ID da oferta."),
    active: z2.boolean().describe("true para reativar, false para pausar.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id, active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("offers").update({ active }).eq("id", offer_id).select("id, title, active").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Oferta n\xE3o encontrada ou sem permiss\xE3o." }], isError: true };
    return {
      content: [{ type: "text", text: `Oferta "${data.title}" ${data.active ? "reativada" : "pausada"}.` }],
      structuredContent: { offer: data }
    };
  }
});

// src/lib/mcp/tools/list-my-leads.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_leads_default = defineTool5({
  name: "list_my_leads",
  title: "Listar meus leads (empresa)",
  description: "Lista os leads recebidos pela empresa logada, mais recentes primeiro.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("M\xE1ximo de leads (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data, error } = await sb.from("leads").select("id, name, phone, email, offer_id, created_at, status").eq("company_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-coupons.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_coupons_default = defineTool6({
  name: "list_my_coupons",
  title: "Listar cupons da empresa",
  description: "Lista cupons emitidos para a empresa logada, com filtro opcional por status (ISSUED, REDEEMED, EXPIRED).",
  inputSchema: {
    status: z4.enum(["ISSUED", "REDEEMED", "EXPIRED"]).optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    let q = sb.from("coupons").select("id, code, customer_name, customer_phone, offer_id, status, expires_at, redeemed_at, created_at").eq("company_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { coupons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-earnings.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_my_earnings_default = defineTool7({
  name: "get_my_earnings",
  title: "Meu saldo e transa\xE7\xF5es",
  description: "Retorna o saldo atual (em centavos) e as \xFAltimas transa\xE7\xF5es do usu\xE1rio logado. \xDAtil para divulgadores e empresas verem movimenta\xE7\xF5es.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("N\xBA de transa\xE7\xF5es (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id, balance").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "Perfil n\xE3o encontrado" }], isError: true };
    const { data: txs, error } = await sb.from("transactions").select("id, type, amount, description, created_at, offer_id").eq("user_id", profile.id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      balance_cents: profile.balance ?? 0,
      balance_reais: ((profile.balance ?? 0) / 100).toFixed(2),
      transactions: txs ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/admin-overview.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
var admin_overview_default = defineTool8({
  name: "admin_overview",
  title: "Overview admin",
  description: "Retorna totais gerais da plataforma: n\xBA de empresas, divulgadores, clientes, ofertas ativas, leads, cupons e saques pendentes. Apenas para usu\xE1rios com papel ADMIN.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const isAdmin = (roles ?? []).some((r) => r.role === "ADMIN");
    if (!isAdmin) {
      return { content: [{ type: "text", text: "Acesso negado: requer papel ADMIN." }], isError: true };
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const [companies, affiliates, clients, offersActive, leads, couponsIssued, couponsRedeemed, withdrawalsPending] = await Promise.all([
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "COMPANY"),
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "AFFILIATE"),
      sb.from("user_roles").select("*", { count: "exact", head: true }).eq("role", "CLIENT"),
      sb.from("offers").select("*", { count: "exact", head: true }).eq("active", true).gt("expires_at", nowIso),
      sb.from("leads").select("*", { count: "exact", head: true }),
      sb.from("coupons").select("*", { count: "exact", head: true }).eq("status", "ISSUED"),
      sb.from("coupons").select("*", { count: "exact", head: true }).eq("status", "REDEEMED"),
      sb.from("withdrawals").select("*", { count: "exact", head: true }).eq("status", "PENDING")
    ]);
    const payload = {
      companies: companies.count ?? 0,
      affiliates: affiliates.count ?? 0,
      clients: clients.count ?? 0,
      active_offers: offersActive.count ?? 0,
      total_leads: leads.count ?? 0,
      coupons_issued: couponsIssued.count ?? 0,
      coupons_redeemed: couponsRedeemed.count ?? 0,
      withdrawals_pending: withdrawalsPending.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sukvjgxxuzophzjcojvd";
var mcp_default = defineMcp({
  name: "clilin-mcp",
  title: "Clilin",
  version: "0.1.0",
  instructions: "Ferramentas do Clilin (plataforma de ofertas locais). Use `whoami` primeiro para descobrir o papel do usu\xE1rio. Empresas podem ver/pausar ofertas, ler leads e cupons. Divulgadores veem saldo e transa\xE7\xF5es. Admins t\xEAm um overview geral. Todas as a\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio logado (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_offers_default,
    list_my_offers_default,
    set_offer_active_default,
    list_my_leads_default,
    list_my_coupons_default,
    get_my_earnings_default,
    admin_overview_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
